# Meta-Orchestrator Standard Benchmark Configuration
# This file defines the official, standardized benchmark experiment for CI/CD.
# It is designed to be fast-running while providing a stable performance signal.

orchestrator:
  type: "standard"
  standard_settings:
    experiments:
      - name: "Standard Benchmark"
        enabled: true
        variants:
          - "in_memory_probe"
          - "slower_reliable_probe"
          - "caching_agent"
        trials_per_variant: 25 # A reasonable number for a CI job

# Global settings
results_dir: "meta_orchestrator/results"

# Scoring weights are fixed for the benchmark to ensure comparability
scoring_weights:
  autonomy: 0.4
  success: 0.35
  cost: -0.15
  latency: -0.1