# Meta-Orchestrator: Causal Analysis Test Configuration
#
# This configuration file is designed specifically to validate the Causal
# Analysis feature by generating clear data for the caching agent.

orchestrator:
  type: "standard"
  standard_settings:
    experiments:
      - name: "Causal Analysis Validation Run"
        enabled: true
        # We focus exclusively on the caching agent to generate clean data
        # regarding the 'was_cached' treatment.
        variants:
          - "caching_agent"
        # We run many trials to ensure a sufficient number of cache misses (on the first run)
        # and cache hits (on subsequent runs).
        trials_per_variant: 40

# Global settings
results_dir: "meta_orchestrator/results"

# Standard scoring weights
scoring_weights:
  autonomy: 0.4
  success: 0.35
  cost: -0.15
  latency: -0.1