# Meta-Orchestrator: Full System Integration Test
#
# This configuration file is designed to exercise all major features of the
# meta-orchestrator in a single, comprehensive run. It validates the
# interaction between different orchestrators, variants, and analysis modules.

orchestrator:
  # We use the standard orchestrator to run multiple, distinct experiments.
  type: "standard"
  standard_settings:
    experiments:
      # --- Experiment 1: A MAB run to find the best simple agent ---
      # Note: This is a conceptual test. In a real scenario, you'd set the
      # orchestrator type to 'mab' for the whole run. This demonstrates
      # flexibility, but isn't a standard use case.
      - name: "MAB Discovery"
        enabled: false # Disabled for now to simplify the test run
        orchestrator: "mab" # A theoretical future feature
        mab_settings:
          strategy: "thompson_sampling"
          total_trials: 100
          variants: ["in_memory_probe", "slower_reliable_probe"]

      # --- Experiment 2: Benchmark of all key agents ---
      - name: "Full Agent Benchmark"
        enabled: true
        variants:
          - "in_memory_probe"
          - "slower_reliable_probe"
          - "caching_agent"
          - "collaborative_agent_team"
        trials_per_variant: 20

      # --- Experiment 3: Causal analysis data generation ---
      - name: "Causal Analysis Data Generation"
        enabled: true
        variants:
          - "caching_agent"
        trials_per_variant: 30 # Generate cache hits and misses

# Global settings
results_dir: "meta_orchestrator/results"

# Standard scoring weights
scoring_weights:
  autonomy: 0.4
  success: 0.35
  cost: -0.15
  latency: -0.1