# Meta-Orchestrator: Collaboration Benchmark Configuration
#
# This configuration file is designed to benchmark the new `CollaborativeAgentTeam`
# against other high-performing variants to determine its effectiveness.

orchestrator:
  type: "standard"
  standard_settings:
    experiments:
      - name: "Collaboration vs. Caching Benchmark"
        enabled: true
        # We will test the new collaborative agent against the caching agent,
        # which is stateful, and the best stateless agent.
        variants:
          - "slower_reliable_probe"
          - "caching_agent"
          - "collaborative_agent_team" # The new agent to be tested
        trials_per_variant: 50 # A high number of trials for statistical significance

# Global settings
results_dir: "meta_orchestrator/results"

# We use the standard scoring weights to ensure a fair comparison
scoring_weights:
  autonomy: 0.4
  success: 0.35
  cost: -0.15
  latency: -0.1